### ISSUE TITLE
so sorry

### ISSUE THREAD

**Issue by tobiKaboom** [SalaniLeo/SalaniLeo-Classeviva#1]
i don't want to be that guy opening an issue just to say something like that one crazy guy on https://github.com/cia-foundation/TempleOS/issues/18 but i just wanted to thank you for making this! im an italian student too and i hate classeviva, so i was thinking about making my own frontend but hey, you have one so that's pretty epic.

**Comment by SalaniLeo** [comment]
hey, don't worry for opening an issue here, I made this project just for fun. I appreciate this comment a lot thank you!
No need to say sorry :D

**Comment by tobiKaboom** [comment]
i wanted to tell you this somewhere else but i dont have linkedin or instagram and i (justifyably, i think) don't really want to share a phone number with a random stranger for telegram. thanks again!

**Comment by SalaniLeo** [comment]
if you don't want to use socials or give your number (understandably) to strangers I suggest you to look into matrix, that said if you have other things to say you can just add me on there! (u can also use that for others so you don't need to open an issue :P)

**Comment by tobiKaboom** [comment]
i'll look into matrix, thanks! i think i tried to create an account once when i wanted to contribute a little to gnome but it was blocking both my gmail and proton accounts for spam, lol. i'll close the issue now!
